# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/todo.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/todo.proto\x12\x04todo\"@\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\x12\x0b\n\x03\x64\x61y\x18\x04 \x01(\x04\"A\n\x11\x43reateTodoRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tcompleted\x18\x02 \x01(\x08\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x04\".\n\x12\x43reateTodoResponse\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.Todo\"\x12\n\x10ListTodosRequest\".\n\x11ListTodosResponse\x12\x19\n\x05todos\x18\x01 \x03(\x0b\x32\n.todo.Todo\"\x1c\n\x0eGetTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x04\"+\n\x0fGetTodoResponse\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.Todo\"\x1f\n\x11\x44\x65leteTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x04\"%\n\x12\x44\x65leteTodoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"M\n\x11UpdateTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\x12\x0b\n\x03\x64\x61y\x18\x04 \x01(\x04\".\n\x12UpdateTodoResponse\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.Todo2\xe4\x02\n\x0bTodoService\x12\x45\n\x10\x63reate_todo_item\x12\x17.todo.CreateTodoRequest\x1a\x18.todo.CreateTodoResponse\x12\x42\n\x0flist_todo_items\x12\x16.todo.ListTodosRequest\x1a\x17.todo.ListTodosResponse\x12<\n\rget_todo_item\x12\x14.todo.GetTodoRequest\x1a\x15.todo.GetTodoResponse\x12\x45\n\x10\x64\x65lete_todo_item\x12\x17.todo.DeleteTodoRequest\x1a\x18.todo.DeleteTodoResponse\x12\x45\n\x10update_todo_item\x12\x17.todo.UpdateTodoRequest\x1a\x18.todo.UpdateTodoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TODO']._serialized_start=27
  _globals['_TODO']._serialized_end=91
  _globals['_CREATETODOREQUEST']._serialized_start=93
  _globals['_CREATETODOREQUEST']._serialized_end=158
  _globals['_CREATETODORESPONSE']._serialized_start=160
  _globals['_CREATETODORESPONSE']._serialized_end=206
  _globals['_LISTTODOSREQUEST']._serialized_start=208
  _globals['_LISTTODOSREQUEST']._serialized_end=226
  _globals['_LISTTODOSRESPONSE']._serialized_start=228
  _globals['_LISTTODOSRESPONSE']._serialized_end=274
  _globals['_GETTODOREQUEST']._serialized_start=276
  _globals['_GETTODOREQUEST']._serialized_end=304
  _globals['_GETTODORESPONSE']._serialized_start=306
  _globals['_GETTODORESPONSE']._serialized_end=349
  _globals['_DELETETODOREQUEST']._serialized_start=351
  _globals['_DELETETODOREQUEST']._serialized_end=382
  _globals['_DELETETODORESPONSE']._serialized_start=384
  _globals['_DELETETODORESPONSE']._serialized_end=421
  _globals['_UPDATETODOREQUEST']._serialized_start=423
  _globals['_UPDATETODOREQUEST']._serialized_end=500
  _globals['_UPDATETODORESPONSE']._serialized_start=502
  _globals['_UPDATETODORESPONSE']._serialized_end=548
  _globals['_TODOSERVICE']._serialized_start=551
  _globals['_TODOSERVICE']._serialized_end=907
# @@protoc_insertion_point(module_scope)
